### 1. 向量和矩阵操作

**创建矩阵**

In [2]:
import numpy as np

In [4]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
a.shape

(2, 3)

In [11]:
# 可以不指定某一个维度的值，给-1，系统自动计算维度
b = np.arange(24).reshape(2,-1,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
#  如果维度不匹配会报错
c = np.arange(6).reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [12]:
# 0矩阵
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# 1矩阵
np.ones( (3,4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# 单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**矩阵运算**

In [3]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a-b

array([20, 29, 38, 47])

In [4]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )

In [5]:
# element-wise乘法
A * B

array([[2, 0],
       [0, 4]])

In [6]:
# 矩阵乘法
A.dot(B)

array([[5, 4],
       [3, 4]])

In [7]:
# 转置
B.transpose()

array([[2, 3],
       [0, 4]])

In [9]:
np.linalg.inv(B)

array([[ 5.00000000e-01,  1.85037171e-17],
       [-3.75000000e-01,  2.50000000e-01]])