### 1. 向量和矩阵操作

**创建矩阵**

In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.shape

(2, 3)

In [4]:
# 可以不指定某一个维度的值，给-1，系统自动计算维度
b = np.arange(24).reshape(2,-1,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
b.shape

(2, 3, 4)

In [6]:
#  如果维度不匹配会报错
c = np.arange(6).reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [7]:
# 0矩阵
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# 1矩阵
np.ones( (3,4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# 单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**矩阵运算**

In [10]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a-b

array([20, 29, 38, 47])

In [11]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )

In [12]:
# element-wise乘法
A * B

array([[2, 0],
       [0, 4]])

In [13]:
# 矩阵乘法
A.dot(B)

array([[5, 4],
       [3, 4]])

In [14]:
# 转置
B.transpose()

array([[2, 3],
       [0, 4]])

In [15]:
np.linalg.inv(B)

array([[ 0.5  ,  0.   ],
       [-0.375,  0.25 ]])

**统计**

https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html


ndarray.max([axis, out, keepdims, initial, …])	Return the maximum along a given axis.<br>
ndarray.argmax([axis, out])	Return indices of the maximum values along the given axis.<br>
ndarray.min([axis, out, keepdims, initial, …])	Return the minimum along a given axis.<br>
ndarray.argmin([axis, out])	Return indices of the minimum values along the given axis of a.<br>
ndarray.ptp([axis, out, keepdims])	Peak to peak (maximum - minimum) value along a given axis.<br>
ndarray.clip([min, max, out])	Return an array whose values are limited to [min, max].<br>
ndarray.conj()	Complex-conjugate all elements.<br>
ndarray.round([decimals, out])	Return a with each element rounded to the given number of decimals.<br>
ndarray.trace([offset, axis1, axis2, dtype, out])	Return the sum along diagonals of the array.<br>
ndarray.sum([axis, dtype, out, keepdims, …])	Return the sum of the array elements over the given axis.<br>
ndarray.cumsum([axis, dtype, out])	Return the cumulative sum of the elements along the given axis.<br>
ndarray.mean([axis, dtype, out, keepdims])	Returns the average of the array elements along given axis.<br>
ndarray.var([axis, dtype, out, ddof, keepdims])	Returns the variance of the array elements, along given axis.<br>
ndarray.std([axis, dtype, out, ddof, keepdims])	Returns the standard deviation of the array elements along given axis.<br>
ndarray.prod([axis, dtype, out, keepdims, …])	Return the product of the array elements over the given axis<br>
ndarray.cumprod([axis, dtype, out])	Return the cumulative product of the elements along the given axis.<br>
ndarray.all([axis, out, keepdims])	Returns True if all elements evaluate to True.<br>
ndarray.any([axis, out, keepdims])	Returns True if any of the elements of a evaluate to True.<br>

In [16]:
a

array([20, 30, 40, 50])

In [17]:
a.max()

50

In [18]:
a.cumsum()

array([ 20,  50,  90, 140])

**拼接/分割**

In [19]:
np.concatenate([a,a], axis=0)

array([20, 30, 40, 50, 20, 30, 40, 50])

In [20]:
np.concatenate([a,a], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [25]:
a2 = np.expand_dims(a,axis=0)
a2

array([[20, 30, 40, 50]])

In [29]:
np.vstack([a2,a2])

array([[20, 30, 40, 50],
       [20, 30, 40, 50]])

In [30]:
np.split(a,2)

[array([20, 30]), array([40, 50])]

**广播**


首先用下面的图直观感受一下：<br>
![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

规则总结：某一个维度是1，其他维度相同，数据复制（广播）

### 官方文档
https://docs.scipy.org/doc/numpy/user/quickstart.html